require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PisosController do

  # This should return the minimal set of attributes required to create a valid
  # Piso. As you add validations to Piso, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PisosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all pisos as @pisos" do
      piso = Piso.create! valid_attributes
      get :index, {}, valid_session
      assigns(:pisos).should eq([piso])
    end
  end

  describe "GET show" do
    it "assigns the requested piso as @piso" do
      piso = Piso.create! valid_attributes
      get :show, {:id => piso.to_param}, valid_session
      assigns(:piso).should eq(piso)
    end
  end

  describe "GET new" do
    it "assigns a new piso as @piso" do
      get :new, {}, valid_session
      assigns(:piso).should be_a_new(Piso)
    end
  end

  describe "GET edit" do
    it "assigns the requested piso as @piso" do
      piso = Piso.create! valid_attributes
      get :edit, {:id => piso.to_param}, valid_session
      assigns(:piso).should eq(piso)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Piso" do
        expect {
          post :create, {:piso => valid_attributes}, valid_session
        }.to change(Piso, :count).by(1)
      end

      it "assigns a newly created piso as @piso" do
        post :create, {:piso => valid_attributes}, valid_session
        assigns(:piso).should be_a(Piso)
        assigns(:piso).should be_persisted
      end

      it "redirects to the created piso" do
        post :create, {:piso => valid_attributes}, valid_session
        response.should redirect_to(Piso.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved piso as @piso" do
        # Trigger the behavior that occurs when invalid params are submitted
        Piso.any_instance.stub(:save).and_return(false)
        post :create, {:piso => { "name" => "invalid value" }}, valid_session
        assigns(:piso).should be_a_new(Piso)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Piso.any_instance.stub(:save).and_return(false)
        post :create, {:piso => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested piso" do
        piso = Piso.create! valid_attributes
        # Assuming there are no other pisos in the database, this
        # specifies that the Piso created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Piso.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => piso.to_param, :piso => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested piso as @piso" do
        piso = Piso.create! valid_attributes
        put :update, {:id => piso.to_param, :piso => valid_attributes}, valid_session
        assigns(:piso).should eq(piso)
      end

      it "redirects to the piso" do
        piso = Piso.create! valid_attributes
        put :update, {:id => piso.to_param, :piso => valid_attributes}, valid_session
        response.should redirect_to(piso)
      end
    end

    describe "with invalid params" do
      it "assigns the piso as @piso" do
        piso = Piso.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Piso.any_instance.stub(:save).and_return(false)
        put :update, {:id => piso.to_param, :piso => { "name" => "invalid value" }}, valid_session
        assigns(:piso).should eq(piso)
      end

      it "re-renders the 'edit' template" do
        piso = Piso.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Piso.any_instance.stub(:save).and_return(false)
        put :update, {:id => piso.to_param, :piso => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested piso" do
      piso = Piso.create! valid_attributes
      expect {
        delete :destroy, {:id => piso.to_param}, valid_session
      }.to change(Piso, :count).by(-1)
    end

    it "redirects to the pisos list" do
      piso = Piso.create! valid_attributes
      delete :destroy, {:id => piso.to_param}, valid_session
      response.should redirect_to(pisos_url)
    end
  end

end
